environment:
  # Need this to set up compilation on Windows.
  CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
  
  PROJECT_NAME: serpentine
  
  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

install:
    # Clone simply to get the script for setting up Windows build environment.
    - cmd: git clone https://github.com/pelson/Obvious-CI.git
    - C:\Python36\python.exe -m pip -m pip install -r requirements.txt
    - C:\Python36\python.exe -m pip install -e .

# Skip .NET project specific build phase.
build: off

test_script:
    # Install the package
    - python3 -m pip install C:\projects\%PROJECT_NAME% pytest
