language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
  - PROJECT_NAME=serpentine
  - GITHUB_REPO_NAME=koszullab/serpentine
os:
- linux
install:
- pip install -r requirements.txt
- pip install pytest pylint pytest-pylint 
- pip install pytest-cov codecov
- if [[ $PYVER == "3.4" ]]; then
    pip install typing requests;
  fi
- if [[ $PYVER == "3.6" ]]; then
    pip install six==1.11;
  fi
- python setup.py install
script:
- pytest --pylint --pylint-error-types=EF --pylint-rcfile=.pylintrc --doctest-modules serpentine
- cd tests;pytest --cov=serpentine
- |
  if [[ $TRAVIS_TAG ]]; then
    python setup.py sdist;
  fi
tags: true
